name: Test and Publish Coder Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_NAME: "kubernetes"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Set up Coder CLI
        uses: coder/setup-action@v1
        with:
          access_url: "https://coder.frantchenco.page"
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}

      - name: Terraform lint and format check (PR only)
        if: github.event_name == 'pull_request'
        run: |
          terraform fmt -check -diff
          terraform validate
        working-directory: template-kubernetes

      - name: Validate Terraform template
        if: github.event_name == 'push'
        run: terraform validate
        working-directory: template-kubernetes

      - name: Get short commit SHA to use as template version name
        id: name
        run: echo "version_name=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get latest commit title to use as template version description
        id: message
        run: echo "pr_title=$(git log --format=%s -n 1 ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Push template to Coder
        run: |
          cd template-kubernetes
          coder templates push $TEMPLATE_NAME --activate=false --name ${{ steps.name.outputs.version_name }} --message "${{ steps.message.outputs.pr_title }}" --yes

      - name: Test template deployment with temporary workspace (PR only)
        if: github.event_name == 'pull_request'
        run: |
          # Create temporary workspace with commit SHA for testing
          WORKSPACE_NAME="test-${{ steps.name.outputs.version_name }}"
          echo "Creating temporary workspace: $WORKSPACE_NAME"
          coder create -t $TEMPLATE_NAME --template-version ${{ steps.name.outputs.version_name }} $WORKSPACE_NAME --parameter namespace=default --parameter use_kubeconfig=false --parameter cpu=2 --parameter memory=2 --parameter home_disk_size=10 --yes
          # Verify workspace was created successfully
          echo "Verifying workspace deployment..."
          coder show $WORKSPACE_NAME

      - name: Cleanup test workspace (PR only)
        if: always() && github.event_name == 'pull_request'
        run: |
          WORKSPACE_NAME="test-${{ steps.name.outputs.version_name }}"
          echo "Cleaning up temporary workspace: $WORKSPACE_NAME"
          coder delete $WORKSPACE_NAME --yes

      - name: Deploy new version (main branch only)
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Promoting template version ${{ steps.name.outputs.version_name }} to production"
          coder template version promote --template=$TEMPLATE_NAME --template-version=${{ steps.name.outputs.version_name }} --yes
