name: Update Coder Template

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # only needed if your action pushes commits, etc.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: latest_commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get commit title
        id: commit_title
        run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Dry‑run update on PR
        if: github.event_name == 'pull_request'
        uses: matifali/update-coder-template@v3
        with:
          id: kubernetes
          dir: template-kubernetes
          url: https://coder.frantchenco.page
          name: ${{ steps.latest_commit.outputs.hash }}
          message: ${{ steps.commit_title.outputs.title }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
          dry_run: true

      - name: Update Coder Template on main
        if: github.event_name == 'push'
        uses: matifali/update-coder-template@v3
        with:
          id: kubernetes
          dir: template-kubernetes
          url: https://coder.frantchenco.page
          name: ${{ steps.latest_commit.outputs.hash }}
          message: ${{ steps.commit_title.outputs.title }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
